version: '3.8'
services:
  careerhack-dcbot:
    image: us-central1-docker.pkg.dev/tsmccareerhack2024-icsd-grp3/tsmccareerhack2024-icsd-grp3-repository/careerhack-dcbot:1.0.0
    ports:
      - "8765:8765"
    env_file:
      - "dcbot/.env"
    networks:
      - careerhack-network
    volumes:
      - ./dcbot:/app
  careerhack-monitor:
    image: us-central1-docker.pkg.dev/tsmccareerhack2024-icsd-grp3/tsmccareerhack2024-icsd-grp3-repository/careerhack-monitor:1.0.0
    ports:
      - "8080:8080"
    env_file:
      - "monitor/.env"
    networks:
      - careerhack-network
    volumes:
      - ./monitor:/app


networks:
  careerhack-network:
    driver: bridge