name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r dcbot/requirements.txt
        pip install -r monitor/requirements.txt
    - name: Run Pylint
      if: always()
      run: |
        pylint dcbot/ || echo Process completed with exit code $?.
        pylint monitor/
